<script lang="ts">
    import { ChevronDown, File } from "lucide-svelte";
    import jsPDF from 'jspdf';
    
    interface Props {
        data: any[];
        filename?: string;
        variant?: "dropdown" | "icon";
        size?: "sm" | "md" | "lg";
        pdfData?: any; // Raw data for PDF generation
        domain?: string; // Domain name for PDF
        pdfTitle?: string; // Title for PDF
    }

    let { data, filename = "export", variant = "dropdown", size = "sm", pdfData, domain, pdfTitle }: Props = $props();

    let showDropdown = $state(false);

    function exportToJSON() {
        const jsonData = JSON.stringify(data, null, 2);
        downloadFile(jsonData, `${filename}.json`, 'application/json');
        showDropdown = false;
    }

    function exportToCSV() {
        if (!data || data.length === 0) return;
        
        // Get all unique keys from all objects
        const allKeys = new Set<string>();
        data.forEach(item => {
            Object.keys(item).forEach(key => allKeys.add(key));
        });
        
        const headers = Array.from(allKeys);
        const csvRows = [
            headers.join(','), // Header row
            ...data.map(item => 
                headers.map(header => {
                    const value = item[header] || '';
                    // Escape commas and quotes in CSV
                    return typeof value === 'string' && (value.includes(',') || value.includes('"'))
                        ? `"${value.replace(/"/g, '""')}"`
                        : value;
                }).join(',')
            )
        ];
        
        const csvData = csvRows.join('\n');
        downloadFile(csvData, `${filename}.csv`, 'text/csv');
        showDropdown = false;
    }

    function exportToPDF() {
        if (!pdfData || !domain || !pdfTitle) {
            console.error('PDF export requires pdfData, domain, and pdfTitle props');
            return;
        }

        try {
            const pdf = new jsPDF();
            const pageWidth = pdf.internal.pageSize.getWidth();
            const margin = 20;
            const contentWidth = pageWidth - (2 * margin);
            let yPosition = margin;

            // Header
            pdf.setFontSize(20);
            pdf.setFont('helvetica', 'bold');
            pdf.text(pdfTitle, margin, yPosition);
            yPosition += 15;

            pdf.setFontSize(12);
            pdf.setFont('helvetica', 'normal');
            pdf.text(`Domain: ${domain}`, margin, yPosition);
            yPosition += 10;

            pdf.text(`Generated: ${new Date().toLocaleString()}`, margin, yPosition);
            yPosition += 20;

            // Generate DNS content
            generateDNSPDF(pdf, pdfData, margin, contentWidth, yPosition);

            // Footer
            const pageHeight = pdf.internal.pageSize.getHeight();
            pdf.setFontSize(10);
            pdf.setTextColor(128, 128, 128);
            pdf.text('Generated by LDNS.com', margin, pageHeight - 10);

            // Download the PDF
            const pdfFilename = `${filename}.pdf`;
            pdf.save(pdfFilename);
        } catch (error) {
            console.error('PDF generation failed:', error);
            alert('Failed to generate PDF. Please try again.');
        }
        
        showDropdown = false;
    }

    function generateDNSPDF(pdf: jsPDF, dnsData: any, margin: number, contentWidth: number, startY: number) {
        let yPosition = startY;
        const lineHeight = 7;

        // DNS Records Summary
        pdf.setFontSize(16);
        pdf.setFont('helvetica', 'bold');
        pdf.text('DNS Records Summary', margin, yPosition);
        yPosition += 15;

        if (dnsData) {
            pdf.setFontSize(12);
            pdf.setFont('helvetica', 'normal');

            // Count records by type
            const recordCounts: Record<string, number> = {};
            Object.keys(dnsData).forEach(recordType => {
                const records = dnsData[recordType];
                if (Array.isArray(records) && records.length > 0) {
                    recordCounts[recordType] = records.length;
                }
            });

            // Display record counts
            Object.entries(recordCounts).forEach(([type, count]) => {
                pdf.text(`${type}: ${count} record${count !== 1 ? 's' : ''}`, margin, yPosition);
                yPosition += lineHeight;
            });

            yPosition += 10;

            // Detailed Records
            Object.entries(dnsData).forEach(([recordType, records]) => {
                if (Array.isArray(records) && records.length > 0) {
                    // Check if we need a new page
                    if (yPosition > pdf.internal.pageSize.getHeight() - 50) {
                        pdf.addPage();
                        yPosition = margin;
                    }

                    pdf.setFontSize(14);
                    pdf.setFont('helvetica', 'bold');
                    pdf.text(`${recordType} Records`, margin, yPosition);
                    yPosition += 12;

                    pdf.setFontSize(10);
                    pdf.setFont('helvetica', 'normal');

                    records.forEach((record: any) => {
                        if (yPosition > pdf.internal.pageSize.getHeight() - 30) {
                            pdf.addPage();
                            yPosition = margin;
                        }

                        const text = `${record.data} (TTL: ${record.TTL || record.ttl || 'N/A'})`;
                        const lines = pdf.splitTextToSize(text, contentWidth - 10);
                        
                        lines.forEach((line: string) => {
                            pdf.text(line, margin + 5, yPosition);
                            yPosition += lineHeight;
                        });
                        yPosition += 2;
                    });
                    yPosition += 8;
                }
            });
        }
    }

    function downloadFile(content: string, fileName: string, mimeType: string) {
        const blob = new Blob([content], { type: mimeType });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = fileName;
        a.style.display = 'none';
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    }

    function getSizeClasses() {
        switch (size) {
            case "sm":
                return "px-2 py-1 text-xs";
            case "md":
                return "px-3 py-1.5 text-sm";
            case "lg":
                return "px-4 py-2 text-base";
            default:
                return "px-2 py-1 text-xs";
        }
    }

    // Close dropdown when clicking outside
    function handleClickOutside(event: Event) {
        const target = event.target as Element;
        if (!target.closest('.export-dropdown')) {
            showDropdown = false;
        }
    }

    // Add/remove event listener for click outside
    $effect(() => {
        if (showDropdown) {
            document.addEventListener('click', handleClickOutside);
            return () => document.removeEventListener('click', handleClickOutside);
        }
    });
</script>

{#if variant === "dropdown"}
    <div class="relative export-dropdown">
        <button
            onclick={() => showDropdown = !showDropdown}
            class={`${getSizeClasses()} flex items-center gap-1 bg-surface-3 hover:bg-surface-3 text-fg rounded transition-colors`}
            disabled={!data || data.length === 0}
        >
            <File class="w-3 h-3" />
            Export
            <ChevronDown class="w-3 h-3" />
        </button>

        {#if showDropdown}
            <div class="absolute right-0 mt-1 w-32 bg-surface-2 border border-line rounded-md shadow-lg z-50">
                <button
                    onclick={exportToJSON}
                    class="w-full px-3 py-2 text-left text-sm text-fg hover:bg-surface-3 rounded-t-md transition-colors"
                >
                    Export JSON
                </button>
                <button
                    onclick={exportToCSV}
                    class="w-full px-3 py-2 text-left text-sm text-fg hover:bg-surface-3 transition-colors"
                >
                    Export CSV
                </button>
                {#if pdfData && domain && pdfTitle}
                    <button
                        onclick={exportToPDF}
                        class="w-full px-3 py-2 text-left text-sm text-fg hover:bg-surface-3 rounded-b-md transition-colors"
                    >
                        Export PDF
                    </button>
                {/if}
            </div>
        {/if}
    </div>
{:else}
    <!-- Icon variant - just JSON export -->
    <button
        onclick={exportToJSON}
        class={`${getSizeClasses()} flex items-center gap-1 bg-surface-3 hover:bg-surface-3 text-fg rounded transition-colors`}
        disabled={!data || data.length === 0}
        title="Export as JSON"
    >
        <File class="w-3 h-3" />
        {#if size !== "sm"}Export{/if}
    </button>
{/if}